### PR TITLE
[doc] Fix documentation example error

### PR DESCRIPTION
**Pull request by inishchith**
- Fix python interface example of `CoCom` backend under documentation. [Reference](https://github.com/Bitergia/graal/blob/c1dfb0f38183766e69d608cf44ac17d26a3ac47d/graal/backends/core/cocom.py#L75)
- Fix parameter definition. [Reference](https://github.com/Bitergia/graal/blob/c1dfb0f38183766e69d608cf44ac17d26a3ac47d/graal/backends/core/cocom.py#L59)

@jgbarah @valeriocos Please review and let me know if any changes required 😄

### CODE REVIEW

**Comment by inishchith** [comment]
@jgbarah Yeah, i was trying to run CoCom & CoLic backends so found these. thought these would help others who might refer `Readme.md` for starters 😄

**Comment by inishchith** [comment]
@valeriocos Thanks for the review. I've `reset` and made them into a single commit and updated the commit message as required. Let me know if any changes required 😅

**Comment by valeriocos** [comment]
Thank you for the quick reply @inishchith , just a minor thing about the commit message. 
The one below is the current one:
```
* [doc] Fix documentation for Cocom backend

    Fix python interface example of `CoCom` backend under documentation.
* [doc] Fix parameter definition.
```
please change it to:
```
[doc] Fix documentation for Cocom backend

Fix python interface example of `CoCom` backend under documentation and parameter definition in `CoCom` class
```
```

**Comment by inishchith** [comment]
@valeriocos Sorry for that. I've updated the commit message.

**Comment by valeriocos** [comment]
No worries @inishchith . Thank you a lot for your PR (just merged :) )

**Pull request merged**
