### PR TITLE
[graal] Update license and copyright information

### PR DESCRIPTION
**Pull request by sanjana091001**
This PR updates license information for every source code file in Graal. The author names are also updated using a script, https://github.com/vchrombie/accio .

### CODE REVIEW

**Comment by vchrombie** [comment]
Hi @valeriocos.
I was going through PR and the repository.

What about these two files
- https://github.com/chaoss/grimoirelab-graal/blob/master/tests/data/Dockerfile
- https://github.com/chaoss/grimoirelab-graal/blob/master/AUTHORS

**Comment by valeriocos** [comment]
Thank you @sanjana091001 for the PR and @vchrombie for having a look.

- https://github.com/chaoss/grimoirelab-graal/blob/master/tests/data/Dockerfile
This is a dockerfile to test a backend. I wouldn't change it

- https://github.com/chaoss/grimoirelab-graal/blob/master/AUTHORS
Can you update the authors there?

Thanks

**Comment by sanjana091001** [comment]
>
> * https://github.com/chaoss/grimoirelab-graal/blob/master/tests/data/Dockerfile
>   This is a dockerfile to test a backend. I wouldn't change it

@valeriocos  Okay

> * https://github.com/chaoss/grimoirelab-graal/blob/master/AUTHORS
>   Can you update the authors there?
> 

 I have made changes to the AUTHORS file, please have a look. Thank you.

**Comment by sanjana091001** [comment]
@valeriocos That's because the tool I used, uses GitHub API to get author data and I think, Nishchith Shetty has set his name to inishchith. 
https://api.github.com/repos/chaoss/grimoirelab-graal/commits?path=tests/utils.py
Moreover, in his sign-off its inishchith (https://github.com/chaoss/grimoirelab-graal/commit/ec7f195407a7ef3c2f061b0a1cb3fa7e2abbfdfe)

**Comment by valeriocos** [comment]
Ok, thank you for the clarification @sanjana091001

**Pull request merged**
