### PR TITLE
Fix some stuff to have a reasonable pip package

### PR DESCRIPTION
**Pull request by jgbarah**
Import grimoirelab_toolkit instead of grimoirelab.toolkit.
Some documentation on installing cloc.
Version back to 0.1.0, reserving for future improvements.

I already uploaded a package to pypi with these changes, so please accept them ;-)

### CODE REVIEW

**Comment by jgbarah** [comment]
@valeriocos I don't know if this still makes sense, or maybe you already added these changes yourself... Please, have a look, since this should be fixed for including Graal in the next GrimoireLab release...

**Comment by valeriocos** [comment]
Sorry for the late reply @jgbarah , I didn't see your PR. 
The changes in [graal/graal.py](https://github.com/chaoss/grimoirelab-graal/pull/1/files#diff-7b65200aee05a2e6c0e0fcd5cc417bafR32) have been already included in the code base, the remaining ones are not.
If you want to fix the conflicts in your PR, I'll merge it (sorry for the inconvenience).

**Comment by valeriocos** [comment]
ping @jgbarah , let me know how you want to proceed

**Comment by jgbarah** [comment]
I saw most of the patch is already in, so I just left the changes to `README.md`, which I think are still appropriate.

**Comment by jgbarah** [comment]
Oooops. I just realized the little change I was proposing in the README file is already in a different section of it. So, this patch is no longer needed. Sorry for the noise.

**Pull request closed without merging**
